# Generated by Django 4.0.5 on 2023-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gcompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('searching', models.CharField(blank=True, max_length=10, null=True)),
                ('apply_detail', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=10)),
                ('work_place', models.CharField(max_length=10)),
            ],
        ),
    ]
