# Generated by Django 4.0.5 on 2023-08-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantee', '0002_alter_gcompany_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcompany',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
