# Generated by Django 4.0.5 on 2023-08-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_number', models.IntegerField()),
                ('company_address', models.CharField(max_length=50)),
                ('company_call', models.CharField(max_length=50)),
                ('company_boss', models.CharField(max_length=10)),
                ('company_size', models.IntegerField(blank=True, null=True)),
                ('company_homepage', models.CharField(blank=True, max_length=50, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('work_place', models.CharField(max_length=50)),
                ('work_day', models.CharField(max_length=50)),
                ('work_hour', models.CharField(max_length=20)),
                ('work_pay', models.CharField(max_length=10)),
                ('work_term', models.CharField(blank=True, max_length=20, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=10, null=True)),
                ('apply_num', models.IntegerField()),
                ('apply_deadline', models.CharField(max_length=20)),
                ('apply_sex', models.CharField(max_length=10)),
                ('apply_age', models.IntegerField()),
                ('apply_work', models.CharField(max_length=20)),
                ('apply_detail', models.CharField(max_length=20)),
            ],
        ),
    ]
