# Generated by Django 4.0.5 on 2023-08-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
